source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

def assets_picker
    pod 'PPAssetsActionController', :path => '../'
end


target 'PPAssetsActionController_Example' do
  assets_picker
end

target 'PPAssetsActionController_Tests' do
  assets_picker
  pod 'KIF'
  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
end
