source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

use_frameworks!

def assets_picker
    pod 'PPAssetsActionController', :path => '../'
end


target 'PPAssetsActionController_Example' do
  assets_picker
end

target 'PPAssetsActionController_Tests' do
  assets_picker
  pod 'KIF'
  pod 'Quick'
  pod 'Nimble'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots', :git => 'git@github.com:danielsaidi/Nimble-Snapshots.git', :branch => 'swift4'
end
