use_frameworks!

target 'PPAssetsActionController_Example' do
  pod 'PPAssetsActionController', :path => '../'

  target 'PPAssetsActionController_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
